### PR TITLE
[Draft] create mschart charts

### PR DESCRIPTION
**Pull request by JanMarvin**
Derived from #219 using https://github.com/ardata-fr/mschart from @davidgohel. Stumbled over mschart today ...err yesterday. Maybe we can use the xml creating code somehow.

```R
# remotes::install_github("JanMarvin/openxlsx2", ref = "mschart")

library(mschart)
library(openxlsx2)

wb <- wb_workbook()

### Scatter
scatter <- ms_scatterchart(data = iris, x = "Sepal.Length", y = "Sepal.Width", group = "Species")
scatter <- chart_settings(scatter, scatterstyle = "marker")

wb <- wb_add_mschart(wb, dims = "F4:L20", graph = scatter)


### Line
chart_01 <- ms_linechart(
  data = us_indus_prod,
  x = "date", y = "value",
  group = "type"
)

chart_01 <- chart_ax_x(
  x = chart_01, num_fmt = "[$-fr-FR]mmm yyyy",
  limit_min = min(us_indus_prod$date), limit_max = as.Date("1992-01-01")
)

chart_01 <- chart_data_stroke(
  x = chart_01,
  values = c(adjusted = "red", unadjusted = "gray")
)

chart_01 <- chart_data_line_width(
  x = chart_01,
  values = c(adjusted = 2, unadjusted = 1)
)

wb <- wb_add_mschart(wb, dims = "F4:L20", graph = chart_01)

### bar chart

chart_01 <- ms_barchart(
  data = browser_data, x = "browser",
  y = "value", group = "serie"
)
chart_01 <- chart_settings(
  x = chart_01, dir = "vertical",
  grouping = "clustered", gap_width = 50
)
chart_01 <- chart_ax_x(
  x = chart_01, cross_between = "between",
  major_tick_mark = "out"
)
chart_01 <- chart_ax_y(
  x = chart_01, cross_between = "midCat",
  major_tick_mark = "in"
)

wb <- wb_add_mschart(wb, dims = "F4:L20", graph = chart_01)


### Area

ac_01 <- ms_areachart(data = browser_ts, x = "date",
                      y = "freq", group = "browser")
ac_01 <- chart_ax_y(ac_01, cross_between = "between", num_fmt = "General")
ac_01 <- chart_ax_x(ac_01, cross_between = "midCat", num_fmt = "m/d/yy")

wb <- wb_add_mschart(wb, dims = "F4:L20", graph = ac_01)

### done
wb$open()
```

Screenshot 2022-11-08 at 01 00 17

### CODE REVIEW

**Comment by JanMarvin** [comment]
Updated the example to use `wb_add_mschart()`. This uses the internal function `mschart::::format.ms_chart()`. What can I say, it works. The example above creates four sheets in a single workbook containing the data and the graphs :)

But I had something different in mind for `openxlsx2`. `mschart` basically brings its own data, while I want a certain data area to be the data source for the graph.

**Comment by davidgohel** [comment]
@JanMarvin sorry, I don't have enough available time for now to help on that. But I agree, it would be good that data area could be the data source. Also if you need an exportation (`mschart:::format.ms_chart`), let me know.

**Comment by JanMarvin** [comment]
Thanks, I basically stumbled over your package yesterday night. I'll have a look

**Comment by JanMarvin** [comment]
@davidgohel I opened a PR in `mschart` to export `format.ms_chart()` and took a closer look at `mschart` last night. The open PR would make it easier for me to finalize this PR.
The question of the data range as data source is another issue. However, I have not yet decided how to proceed. Unfortunately, it looks like a bit more work than I had hoped to do to customize `mschart` to my needs.

**Pull request closed without merging**
