### PR TITLE
[R/add_border] add_border and wb_add_border

### PR DESCRIPTION
**Pull request by JanMarvin**
Create borders for cell regions. This creates border styles for a specific region.

* [x] add tests
* [x] merge styles if possible. If cell as `<xf../>` node, copy the node and applyBorder and borderid. Otherwise if two or more cells share the style, they all would get the border.
* [x] inner grid (maybe providing a single style)

### CODE REVIEW

**Comment by JanMarvin** [comment]
unrelated fix for showGridLines option and newly introduced rowColHeaders option.

**Comment by JanMarvin** [comment]
Any clue why the test are complaining @jmbarbone ?

**Comment by jmbarbone** [comment]
> Any clue why the test are complaining @jmbarbone ?

@JanMarvin, it looks like some weird `roxygen2` behavior where the the lines changes in 
237a1bd were being appended to the documentation.

**Comment by JanMarvin** [comment]
Thanks, didn't see that. Maybe because of the example in the `wbWorkbook` part

**Pull request merged**
