### PR TITLE
576 add twoCellAnchor option to add_image function

### PR DESCRIPTION
**Pull request by rfineman**
Resolves enhancement #576.

- update wb_add_image wrapper function
- update add_image internal function in workbook
- update add_plot internal function in workbook

### CODE REVIEW

**Comment by rfineman** [comment]
@JanMarvin if you like this enhancement, wasn't sure if you were comfortable renaming rowOffset/colOffset to startRowOffset/startColOffset as it would lead to breaking change. If preferred, we can keep rowOffset/colOffset and then also include startRowOffset/startColOffset that take rowOffset/colOffset as the default value.

Additionally, only changed add_plot to act the same way it currently operations. We could modify that as well, however have the additional hitch of how we wish to handle xy paramater.

**Comment by JanMarvin** [comment]
Thanks for the issue and the pull request. I'll have a look tomorrow or after Easter. For drawings we have something in place that selects one or two cell anchor depending on dims. No dims is absolute, single cell is one cell anchor and cell range is two cell anchor. Can't we use something like that for images as well?

**Comment by JanMarvin** [comment]
Hi @rfineman , thanks again for the PR. Based on your suggestion I have pushed #578 which supersedes this PR. Please let me know if this is what you are looking for.

**Comment by rfineman** [comment]
@JanMarvin like your solution. works perfectly for my need. thanks.

**Pull request closed without merging**
