### PR TITLE
[pt] add choose param

### PR DESCRIPTION
**Pull request by JanMarvin**
Works in Libreoffice

ping @vorpalvorpal

``` r
library(openxlsx2)

example_df <- data.frame(
  type = c("EU", "US", "US", "EU", "EU", "EU"),
  location = c("London", "NYC", "NYC", "Berlin", "Madrid", "London"),
  amount = c(7, 5, 3, 2.5, 6, 1)
)

wb <- wb_workbook() %>% 
  wb_add_worksheet() %>% 
  wb_add_data(x = example_df)

df <- wb_data(wb)

wb <- wb %>%
  wb_add_pivot_table(
    df, dims = "A3", rows = "location", filter = "type", data = "amount",
    slicer = "location", pivot_table = "pt1",
    param = list(
      choose = c(type = 'x=="EU"', 
                 location = 'x %in% c("London", "Madrid")')
      )
  )

if (interactive()) wb$open()
```

### CODE REVIEW

**Comment by JanMarvin** [comment]
``` r
library(openxlsx2)

example_df <- data.frame(
  type = c("EU", "US", "US", "EU", "EU", "EU"),
  location = c("London", "NYC", "NYC", "Berlin", "Madrid", "London"),
  amount = c(7, 5, 3, 2.5, 6, 1)
)

wb <- wb_workbook() %>% 
  wb_add_worksheet() %>% 
  wb_add_data(x = example_df)

df <- wb_data(wb)

wb <- wb %>%
  wb_add_pivot_table(
    df, dims = "A3", rows = "location", filter = "type", data = "amount",
    slicer = "location", pivot_table = "pt1",
    param = list(
      choose = c(type = 'x=="EU"')
    )
  ) %>% 
  wb_add_slicer(
    x = df, dims = "E2", 
    slicer = "location", pivot_table = "pt1", 
    param = list(
      choose = c(
        location = 'x %in% c("London", "Madrid")'
      )
    )
  )

if (interactive()) wb$open()
```

**Comment by JanMarvin** [comment]
There might be some quirks with escaped xml, like selecting "A&B" must be escaped as "A&amp;B", but I was to lazy to fix that correctly. Also I didn't test that it works correctly with item sorting, but it's a start.

**Comment by vorpalvorpal** [comment]
Wow! That works great! 
Sorry, I had meant to actually contribute something, but you beat me to it.

**Comment by JanMarvin** [comment]
Oops, haha. This was just in the back of my head and I was interested to see how the eval stuff would work.

There’s always something to do. Especially with testing and documenting all helping hands are more than welcome. And it’s kinda hard to test pivot table functionality with base R.

**Pull request merged**
