### PR TITLE
Release 1.1

### PR DESCRIPTION
**Pull request by JanMarvin**
## prepare
* [x] check vignette code validity
* [x] `roxygen2::roxygenize()`
* [x] `spelling::update_wordlist()`
* [x] `spelling::spell_check_package()`
* [x] `lintr::lint_package()`
* [x] `R CMD build openxlsx2`
* [x] `R CMD check --as-cran`
* [x] run revdep
* [x] update NEWS

## submission
* 2023-10-23: First submission to CRAN
* 2023-10-23: Second submission to CRAN: Adressing R-Devel CMD check NOTEs

### CODE REVIEW

**Comment by JanMarvin** [comment]
@olivroy [CRAN pretest](https://win-builder.r-project.org/incoming_pretest/openxlsx2_1.1_20231023_093548/Debian/00check.log) complained: since you are the one who has written/updated most of these recently. Could you please have a look?

**Comment by JanMarvin** [comment]
I've added a fix. Maybe not the most elegant, but at least it does the job

**Comment by JanMarvin** [comment]
The re-submission is on its way. The CRAN Windows test complained on the r-universe link and needs a manual inspection by a CRAN team member.

```
Found the following (possibly) invalid URLs:
  URL: https://janmarvin.r-universe.dev/openxlsx2
    From: README.md
    Status: Error
    Message: Recv failure: Connection was reset
  URL: https://r-universe.dev/
    From: README.md
    Status: Error
    Message: Recv failure: Connection was reset
```

**Comment by olivroy** [comment]
Glad it worked! looking forward to the feedback on the again awesome work you put in the 1.1 release

**Comment by JanMarvin** [comment]
Thanks for the kind words!

**Pull request merged**
