### PR TITLE
[R/save] use dir.exist(). closes #263

### LINKED ISSUE #263: Check tmpDir with `dir.exists()`
Check if we should port from PR https://github.com/ycphs/openxlsx/pull/364 by @christianrickert.

### PR DESCRIPTION
**Pull request by JanMarvin**
"Forward-port" https://github.com/ycphs/openxlsx/pull/364 from @christianrickert. Would be super nice, if you could check that this is still sufficient to fix your issue, @christianrickert (it's rather unlikely that I'll ever end up with your specific setup).

A basic command to write a file with `openxlsx2` would be:
```R
# remotes::install_github("JanMarvin/openxlsx2", ref = "gh_issue_263")
library(openxlsx2)
wb_workbook() %>% 
  wb_add_worksheet() %>% 
  wb_add_data(x = mtcars) %>% 
  wb_save("mtcars.xlsx")
```

[Edit:] added `ref` to remotes install.

### CODE REVIEW

**Comment by christianrickert** [comment]
Just ran the code with both versions (@head/@gh_issue_263) on my system.
The TEMP/TMP system variables are set to drive `D:\` (USB stick).

From: @head - expecting this to fail
```R console
> remotes::install_github("JanMarvin/openxlsx2")
Downloading GitHub repo JanMarvin/openxlsx2@HEAD
✔  checking for file 'D:\RtmpqSMLGY\remotes34a864c963cf\JanMarvin-openxlsx2-dce5801/DESCRIPTION' (11.1s)
─  preparing 'openxlsx2': (4m 56.5s)
✔  checking DESCRIPTION meta-information ... 
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (25.7s)
─  checking for empty or unneeded directories (10.7s)
─  building 'openxlsx2_0.2.1.9000.tar.gz'
   
* installing *source* package 'openxlsx2' ...
** using staged installation
** libs
[...]
installing to C:/Program Files/R/R-4.2.1/library/00LOCK-openxlsx2/00new/openxlsx2/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (openxlsx2)
> library(openxlsx2)

Attaching package: ‘openxlsx2’

The following object is masked from ‘package:readr’:

    write_file

> wb_workbook() %>% 
+   wb_add_worksheet() %>% 
+   wb_add_data(x = mtcars) %>% 
+   wb_save("mtcars.xlsx")
Error in wb$clone()$save(path = path, overwrite = overwrite) : 
  Failed to create temporary directory 'D:\\RtmpqSMLGY\workbookTemp_34a83c0b173e'
In addition: Warning message:
In dir.create(path = tmpDir, recursive = TRUE) :
  cannot create dir 'D:\', reason 'Permission denied'
> 
```
From: @gh_issue_263 - testing for failure
```R console
> remotes::install_github("JanMarvin/openxlsx2", ref = "gh_issue_263")
Downloading GitHub repo JanMarvin/openxlsx2@gh_issue_263
✔  checking for file 'D:\RtmpY7UPwL\remotes3b6c11ad786d\JanMarvin-openxlsx2-e6ff5ae/DESCRIPTION' (10s)
─  preparing 'openxlsx2': (43.6s)
✔  checking DESCRIPTION meta-information ... 
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (22.2s)
─  checking for empty or unneeded directories (1.2s)
─  building 'openxlsx2_0.2.1.9000.tar.gz'
   
* installing *source* package 'openxlsx2' ...
** using staged installation
** libs
[...]
installing to C:/Program Files/R/R-4.2.1/library/00LOCK-openxlsx2/00new/openxlsx2/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures```

** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (openxlsx2)
> library(openxlsx2)
> wb_workbook() %>% 
+   wb_add_worksheet() %>% 
+   wb_add_data(x = mtcars) %>% 
+   wb_save("mtcars.xlsx")
Error in file(file.path(xlthemeDir, "theme1.xml"), open = "wb") : 
  cannot open the connection
In addition: Warning messages:
1: In dir.create(path, showWarnings = warn, recursive = recurse) :
  cannot create dir 'D:\', reason 'Permission denied'
2: In dir.create(path, showWarnings = warn, recursive = recurse) :
  cannot create dir 'D:\', reason 'Permission denied'
3: In dir.create(path, showWarnings = warn, recursive = recurse) :
  cannot create dir 'D:\', reason 'Permission denied'
4: In dir.create(path, showWarnings = warn, recursive = recurse) :
  cannot create dir 'D:\', reason 'Permission denied'
5: In dir.create(path, showWarnings = warn, recursive = recurse) :
  cannot create dir 'D:\', reason 'Permission denied'
6: In dir.create(path, showWarnings = warn, recursive = recurse) :
  cannot create dir 'D:\', reason 'Permission denied'
7: In dir.create(path, showWarnings = warn, recursive = recurse) :
  cannot create dir 'D:\', reason 'Permission denied'
8: In file(file.path(xlthemeDir, "theme1.xml"), open = "wb") :
  cannot open file 'D:\\RtmpY7UPwL\workbookTemp_3b6c66325311/xl/theme/theme1.xml': No such file or directory
> 
```
Same issues as before - is the `recurse` variable set to TRUE?

**Comment by JanMarvin** [comment]
Thanks for the follow up, it was `TRUE` indeed. Changed it to `FALSE` though unsure about the implications.

**Comment by christianrickert** [comment]
It worked with the latest changes.

Here's the R console output from RStudio:
```R console
> tempdir()
[1] "D:\\\\RtmpGIwyET"
> library(openxlsx2)
> wb_workbook() %>% 
+   wb_add_worksheet() %>% 
+   wb_add_data(x = mtcars) %>% 
+   wb_save("mtcars.xlsx")
[1] "mtcars.xlsx"
```
Here's the output from the Microsoft Excel sheet:
> 
mpg | cyl | disp | hp | drat | wt | qsec | vs | am | gear | carb
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
21 | 6 | 160 | 110 | 3.9 | 2.62 | 16.46 | 0 | 1 | 4 | 4
21 | 6 | 160 | 110 | 3.9 | 2.875 | 17.02 | 0 | 1 | 4 | 4
22.8 | 4 | 108 | 93 | 3.85 | 2.32 | 18.61 | 1 | 1 | 4 | 1
21.4 | 6 | 258 | 110 | 3.08 | 3.215 | 19.44 | 1 | 0 | 3 | 1
18.7 | 8 | 360 | 175 | 3.15 | 3.44 | 17.02 | 0 | 0 | 3 | 2
18.1 | 6 | 225 | 105 | 2.76 | 3.46 | 20.22 | 1 | 0 | 3 | 1
14.3 | 8 | 360 | 245 | 3.21 | 3.57 | 15.84 | 0 | 0 | 3 | 4
24.4 | 4 | 146.7 | 62 | 3.69 | 3.19 | 20 | 1 | 0 | 4 | 2
22.8 | 4 | 140.8 | 95 | 3.92 | 3.15 | 22.9 | 1 | 0 | 4 | 2
19.2 | 6 | 167.6 | 123 | 3.92 | 3.44 | 18.3 | 1 | 0 | 4 | 4
17.8 | 6 | 167.6 | 123 | 3.92 | 3.44 | 18.9 | 1 | 0 | 4 | 4
16.4 | 8 | 275.8 | 180 | 3.07 | 4.07 | 17.4 | 0 | 0 | 3 | 3
17.3 | 8 | 275.8 | 180 | 3.07 | 3.73 | 17.6 | 0 | 0 | 3 | 3
15.2 | 8 | 275.8 | 180 | 3.07 | 3.78 | 18 | 0 | 0 | 3 | 3
10.4 | 8 | 472 | 205 | 2.93 | 5.25 | 17.98 | 0 | 0 | 3 | 4
10.4 | 8 | 460 | 215 | 3 | 5.424 | 17.82 | 0 | 0 | 3 | 4
14.7 | 8 | 440 | 230 | 3.23 | 5.345 | 17.42 | 0 | 0 | 3 | 4
32.4 | 4 | 78.7 | 66 | 4.08 | 2.2 | 19.47 | 1 | 1 | 4 | 1
30.4 | 4 | 75.7 | 52 | 4.93 | 1.615 | 18.52 | 1 | 1 | 4 | 2
33.9 | 4 | 71.1 | 65 | 4.22 | 1.835 | 19.9 | 1 | 1 | 4 | 1
21.5 | 4 | 120.1 | 97 | 3.7 | 2.465 | 20.01 | 1 | 0 | 3 | 1
15.5 | 8 | 318 | 150 | 2.76 | 3.52 | 16.87 | 0 | 0 | 3 | 2
15.2 | 8 | 304 | 150 | 3.15 | 3.435 | 17.3 | 0 | 0 | 3 | 2
13.3 | 8 | 350 | 245 | 3.73 | 3.84 | 15.41 | 0 | 0 | 3 | 4
19.2 | 8 | 400 | 175 | 3.08 | 3.845 | 17.05 | 0 | 0 | 3 | 2
27.3 | 4 | 79 | 66 | 4.08 | 1.935 | 18.9 | 1 | 1 | 4 | 1
26 | 4 | 120.3 | 91 | 4.43 | 2.14 | 16.7 | 0 | 1 | 5 | 2
30.4 | 4 | 95.1 | 113 | 3.77 | 1.513 | 16.9 | 1 | 1 | 5 | 2
15.8 | 8 | 351 | 264 | 4.22 | 3.17 | 14.5 | 0 | 1 | 5 | 4
19.7 | 6 | 145 | 175 | 3.62 | 2.77 | 15.5 | 0 | 1 | 5 | 6
15 | 8 | 301 | 335 | 3.54 | 3.57 | 14.6 | 0 | 1 | 5 | 8
21.4 | 4 | 121 | 109 | 4.11 | 2.78 | 18.6 | 1 | 1 | 4 | 2

Here's the output from the `test_check("openxlsx2")`:
```
// will update once completed
```

The implications depend on the need to actually create a folder structure during runtime recursively.
As far as I can tell, the recursive folder creation isn't used at all.
Instead, parent folders are explicitly created before creating their child folders.
Example:
https://github.com/JanMarvin/openxlsx2/blob/72ff05f569a70345c7cfd379b02e479d98e615f5/R/class-workbook.R#L962
For example:
```R
xlDir               <- dir_create(tmpDir, "xl")  # parent is created here
[...]
xlworksheetsDir     <- dir_create(tmpDir, "xl", "worksheets")  # child 1 is created here
xlworksheetsRelsDir <- dir_create(tmpDir, "xl", "worksheets", "_rels")  # child 2 is created here
```

**Comment by christianrickert** [comment]
I'm currently repeating the tests with openxlsx2@head.

**Comment by JanMarvin** [comment]
> The implications depend on the need to actually create a folder structure during runtime recursively.
> As far as I can tell, the recursive folder creation isn't used at all.
> Instead, parent folders are explicitly created before creating their child folders.

Thanks for checking and testing! Yes, we only create folders explicitly. I thought that it works as `mkdir -p` and that we end up in a scenario, where we have to create the temp folder deep in some other folder. Though that's unlikely.

So we got saving working for us. The other failing tests might use some other resurse option, I haven't checked yet. At first glance I saw some errors regarding missing directories.

**Comment by christianrickert** [comment]
About the `unzip(file, exdir = xmlDir)`: 'exdir' does not exist` error:

For example, [`readWorkbook.R`](https://github.com/JanMarvin/openxlsx2/blob/28388eae295ab9741a9a3f204695af5c5d464f9e/R/readWorkbook.R#L177) the `xmlDir` is created implicitly by calling `unzip` with the `exdir` argument:
> exdir: The directory to extract files to (the equivalent of unzip -d). It will be created if necessary.
I'd suggest to replace the implicit call with an explicit one:
```R
xlDir <- dir_create(tmpDir, "_excelXMLRead")  # create folder here
on.exit(unlink(xmlDir, recursive = TRUE), add = TRUE)  # delete folder afterwards
xmlFiles <- unzip(file, exdir = xmlDir)  # folder not created here, already exists
```

**Comment by christianrickert** [comment]
> I've rebased this on `main`, just to make sure there was no pending issue and I've switched a few more `dir.create()` cases.

Thanks, I'm going to test the updated branch with D:\.

**Comment by JanMarvin** [comment]
> About the `unzip(file, exdir = xmlDir): 'exdir' does not exist` error:
> 
> For example, [`readWorkbook.R`](https://github.com/JanMarvin/openxlsx2/blob/28388eae295ab9741a9a3f204695af5c5d464f9e/R/readWorkbook.R#L177) the `xmlDir` is created implicitly by calling `unzip` with the `exdir` argument:
> 
> > exdir: The directory to extract files to (the equivalent of unzip -d). It will be created if necessary.
> 
> I'd suggest to replace the implicit call with an explicit one:
> 
> ```r
> xlDir <- dir_create(tmpDir, "_excelXMLRead")  # create folder here
> on.exit(unlink(xmlDir, recursive = TRUE), add = TRUE)  # delete folder afterwards
> xmlFiles <- unzip(file, exdir = xmlDir)  # folder not created here, already exists
> ```

Hi, sorry lost track of this issue (and while looking at it I hid your wall of `testthat` output above).

I've rebased once again and added a function to create the required directory explicitly. Though not sure if I got you here correctly. Could you please let me know if this solves the remaining issue(s)?

**Comment by christianrickert** [comment]
> > About the `unzip(file, exdir = xmlDir): 'exdir' does not exist` error:
> > For example, [`readWorkbook.R`](https://github.com/JanMarvin/openxlsx2/blob/28388eae295ab9741a9a3f204695af5c5d464f9e/R/readWorkbook.R#L177) the `xmlDir` is created implicitly by calling `unzip` with the `exdir` argument:
> > > exdir: The directory to extract files to (the equivalent of unzip -d). It will be created if necessary.
> > 
> > 
> > I'd suggest to replace the implicit call with an explicit one:
> > ```r
> > xlDir <- dir_create(tmpDir, "_excelXMLRead")  # create folder here
> > on.exit(unlink(xmlDir, recursive = TRUE), add = TRUE)  # delete folder afterwards
> > xmlFiles <- unzip(file, exdir = xmlDir)  # folder not created here, already exists
> > ```
> 
> Hi, sorry lost track of this issue (and while looking at it I hid your wall of `testthat` output above).
> 
> I've rebased once again and added a function to create the required directory explicitly. Though not sure if I got you here correctly. Could you please let me know if this solves the remaining issue(s)?

(Borat voice) "Great success!"

Both test runs (for `%USERPROFILE%\AppData\Local\Temp` and `D:\` completed successfully!
Example output for `D:\`:
```R
> tempdir()
[1] "D:\\\\RtmpgBtXrG"
[...]
> test_check("openxlsx2")
Starting 2 test processes
[ FAIL 0 | WARN 0 | SKIP 1 | PASS 957 ]

══ Skipped tests ══════════════════════════════════════════════════════════════════════════════════
• empty test (1)

[ FAIL 0 | WARN 0 | SKIP 1 | PASS 957 ]
```
Thanks for the update!

**Comment by JanMarvin** [comment]
Yay! Thanks for testing! Will be merged this week. I'll add a test for this, otherwise it should be fine.

**Comment by christianrickert** [comment]
Thank you very much!

**Pull request merged**
